
country.by.region = list(AFRO = c('ALGERIA', 'ANGOLA', 'BENIN', 'BOTSWANA', 'BURKINA FASO', 'BURUNDI', 'CAMEROON', 'CAPE VERDE', 
                                  'CENTRAL AFRICAN REPUBLIC', 'CHAD', 'COMOROS', 'IVORY COAST', 'DEMOCRATIC REPUBLIC OF THE CONGO', 
                                  'EQUATORIAL GUINEA', 'ERITREA', 'ETHIOPIA', 'GABON', 'GAMBIA', 'GHANA', 'GUINEA', 'GUINEA-BISSAU', 
                                  'KENYA', 'LESOTHO', 'LIBERIA', 'MADAGASCAR', 'MALAWI', 'MALI', 'MAURITANIA', 'MAURITIUS', 'MOZAMBIQUE', 
                                  'NAMIBIA', 'NIGER', 'NIGERIA', 'REPUBLIC OF THE CONGO', 'RWANDA', 'SÃO TOMÉ AND PRÍNCIPE', 'SENEGAL', 
                                  'SEYCHELLES', 'SIERRA LEONE', 'SOMALIA', 'SOUTH AFRICA', 'SOUTH SUDAN', 'ESWATINI', 'TOGO', 'UGANDA', 
                                  'TANZANIA', 'ZAMBIA', 'ZIMBABWE'), 
                         AMRO = c('ANTIGUA AND BARBUDA', 'ARGENTINA', 'BAHAMAS', 'BARBADOS', 'BELIZE', 'BOLIVIA', 'BRAZIL', 'CANADA', 
                                  'CHILE', 'COLOMBIA', 'COSTA RICA', 'CUBA', 'DOMINICA', 'DOMINICAN REPUBLIC', 'ECUADOR', 'EL SALVADOR', 
                                  'GRENADA', 'GUATEMALA', 'GUYANA', 'HAITI', 'HONDURAS', 'JAMAICA', 'MEXICO', 'NICARAGUA', 'PANAMA', 'PARAGUAY', 
                                  'PERU', 'SAINT KITTS AND NEVIS', 'SAINT LUCIA', 'SAINT VINCENT AND THE GRENADINES', 'SURINAME', 'TRINIDAD AND TOBAGO',
                                  'UNITED STATES', 'URUGUAY', 'VENEZUELA'),
                         SEARO = c('BANGLADESH', 'BHUTAN', 'NORTH KOREA', 'INDIA', 'INDONESIA', 'MALDIVES', 'MYANMAR', 'NEPAL', 'SRI LANKA', 
                                   'THAILAND', 'TIMOR-LESTE'), 
                         EURO = c('ALBANIA', 'ANDORRA', 'ARMENIA', 'AUSTRIA', 'AZERBAIJAN', 'BELARUS', 'BELGIUM', 'BOSNIA AND HERZEGOVINA', 
                                  'BULGARIA', 'CROATIA', 'CYPRUS', 'CZECH REPUBLIC', 'DENMARK', 'ESTONIA', 'FINLAND', 'FRANCE', 'GEORGIA', 'GERMANY', 
                                  'GREECE', 'HUNGARY', 'ICELAND', 'IRELAND', 'ISRAEL', 'ITALY', 'KAZAKHSTAN', 'KYRGYZSTAN', 'LATVIA', 'LITHUANIA', 
                                  'LUXEMBOURG', 'MALTA', 'MOLDOVA', 'MONACO', 'MONTENEGRO', 'NETHERLANDS', 'NORTH MACEDONIA', 'NORWAY', 'POLAND', 'PORTUGAL', 
                                  'ROMANIA', 'RUSSIA', 'SAN MARINO', 'SERBIA', 'SLOVAKIA', 'SLOVENIA', 'SPAIN', 'SWEDEN', 'SWITZERLAND', 'TAJIKISTAN', 'TURKEY', 
                                  'TURKMENISTAN', 'UKRAINE', 'UNITED KINGDOM', 'UZBEKISTAN', 'KOSOVO'),
                         EMRO = c('AFGHANISTAN', 'BAHRAIN', 'DJIBOUTI', 'EGYPT', 'IRAN', 'IRAQ', 'JORDAN', 'KUWAIT', 'LEBANON', 'LIBYA', 'MOROCCO', 
                                  'OMAN', 'PAKISTAN', 'PALESTINE', 'QATAR', 'SAUDI ARABIA', 'SOMALIA', 'SUDAN', 'SYRIA', 'TUNISIA', 'UNITED ARAB EMIRATES', 'YEMEN'), 
                         WPRO = c('AUSTRALIA', 'BRUNEI', 'CAMBODIA', 'CHINA', 'COOK ISLANDS', 'FIJI', 'JAPAN', 'KIRIBATI', 'LAOS', 'MALAYSIA', 
                                  'MARSHALL ISLANDS', 'MICRONESIA', 'MONGOLIA', 'NAURU', 'NEW ZEALAND', 'NIUE', 'PALAU', 'PAPUA NEW GUINEA', 'PHILIPPINES', 'SAMOA', 
                                  'SINGAPORE', 'SOLOMON ISLANDS', 'SOUTH KOREA', 'TAIWAN', 'TONGA', 'TUVALU', 'VANUATU', 'VIETNAM'))